server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${MYSQLUSER:sa}
    password: ${MYSQLPASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
  h2:
    console:
      enabled: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
  flyway:
    enabled: false

cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:5173,https://*.railway.app}

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    com.enquirycrm: INFO
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
